services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn daybook.wsgi:application --bind 0.0.0.0:8000"
    plan: free
    branch: main
