# Generated by Django 5.2.1 on 2025-05-13 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
